"""add approvals table

Revision ID: ed9dbecb8de4
Revises: ef902854359d
Create Date: 2026-09-04 11:49:34.637540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9dbecb8de4'
down_revision: Union[str, Sequence[str], None] = 'ef902854359d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='purchaseorderstatus', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('purchase_orders_po_number_key'), 'purchase_orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('purchase_orders_po_number_key'), 'purchase_orders', ['po_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='purchaseorderstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
